version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: fiap-mysql
    restart: always
    environment:
      MYSQL_DATABASE: fiap
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
